import React from 'react';

function test() {
  const obj = {
    dataArea: {
      captureRequest: {
        sysRefNo: '4e30049b-4edc-42a7-a8be-f14e042de1d47do-fab-demo-14',
        initiatedBy: 'balamadesh1234',
        channel: 'PORTAL',
        productType: 'MBBF-BUS',
        source: 'P',
        isWorkitemCreate: 'C',
        folderIndex: '',
        wiUrn: '',
        wiName: '',

      },
      customerDetails: {
        registrationDetails: {
          rmCode: 'saff',
          firstName: 'bala',
          lastName: 'madesh',
          phoneNumber: '243243422',
          emailID: 'balamadesh@gmail.com',
        },
        applicationDetail: {
          appDetailIOrderId: '1234',
          created_date: '',
          new_or_existing_customer: 'New',
          product: 'BA',
          loan_type: 'Fresh',
          loan_account_number: '',
          legal_entity_name: 'Legal1',
          cif_id: '',
          emirates_id: '',
          trade_license_number: 'bond1234',
          branch: '',
          channel: 'PORTAL',
        },
        customerDetail: {
          customeriOrderId: '1234',
          short_name: 'RAM',
          country_of_incorporation: 'AE',
          country_of_domiciles: 'AE',
          business_operation: '',
          date_of_incorporation: '2022-12-20 00:00:00.0',
          website_address: 'www@abc.com',
          emirate_of_registration: 'DUBAI',
          legal_entity_type: 'Free Zone - Offshore',
          legal_entity_category: 'Free Zone Entity',
          primary_industry: 'Maintenance of Building',
          secondary_industry: '',
          number_of_employes: 'null',
          current_company_turnoer: null,
          projected_company_turnover: null,
          sister_company: 'Y',
          legal_entity_name: null,
          group_name: null,
          registration_of_authority: null,
          registration_authority_name: null,
          vat: null,
          fab_sub_segment: null,
          sector: null,
          authorised_signatory: null,
          rollovertype: null,
          customer_status: null,
          business_details_description: null,
        },
        addressDetails: {
          address: [
            {
              addressiOrderId: '1234',
              addressType: 'Correspondence',
              buildingNumber: '123',
              buildingName: 'ABC',
              streetName: 'Dubai',
              locationArea: 'Dubai',
              townCity: 'Dubai',
              zipCode: '600005',
              addressEmirate: 'ABU DHABI',
              addressPoBox: 'PO 67890',
              country: 'AE',
              addressStayingAtThis: '2018-07-12 00:00:00',
              mailingAddress: 'Y',
              primaryMobileNumber: '907890000',
              officeTelephoneNumber: '9023667788',
              homeTelephoneNumber: '890355665',
              fax: '9034566',
              emailAddress: 'zyz@gmail.com',
              nearestLandmark: 'Mall',
            },
          ],
        },
        identityDetails: {
          identity: [
            {
              identityiOrderId: '1234',
              identifiertype: 'PASSPORT',
              number: '134566',
              issuedate: '2020-07-10 00:00:00.0',
              expirydate: '2029-03-01 00:00:00.0',
              placeofissue: 'Dubai',
            },
          ],
        },
      },
    },
  };
  const workItemData = {
    dataArea: {
      captureRequest: {
        sysRefNo: '1672167675521', initiatedBy: 'sanjay11', channel: 'Portal', productType: 'POS', source: 'P', isWorkitemCreate: null, eligibilityStatus: 'null', folderIndex: '6621', wiUrn: 'SME-5083', wiName: 'SME-0000005083-process',
      },
      customerDetails: {
        applicationDetail: {
          appDetailIOrderId: '720', created_date: '', new_or_existing_customer: 'New', product: 'POS', loan_type: 'Fresh', loan_account_number: '', legal_entity_name: 'Legal1', cif_id: '', emirates_id: '', trade_license_number: 'null', branch: '', channel: 'Portal',
        },
        customerDetail: {
          customeriOrderId: '734', short_name: 'testing', country_of_incorporation: 'BN', country_of_domiciles: 'AD', business_operation: 'AD', date_of_incorporation: '2022-12-20 00:00:00.0', website_address: 'test', emirate_of_registration: 'AJMAN', legal_entity_type: 'Representative Office', legal_entity_category: 'Sovereign Wealth Fund', primary_industry: 'TRUSTS', secondary_industry: 'INDIVIDUAL', number_of_employes: 'NOEa', current_company_turnoer: '', projected_company_turnover: 'PCT', sister_company: 'null', legal_entity_name: 'Legal1', group_name: 'test', registration_of_authority: 'Ajman', registration_authority_name: 'trr', vat: 'null', fab_sub_segment: '', sector: '', authorised_signatory: null, rollovertype: null, customer_status: null, business_details_description: 'hdsadh',
        },
        addressDetails: {
          address: [{
            addressiOrderId: '337', addressType: 'Correspondence', buildingNumber: 'test', buildingName: 'test', streetName: 'test', locationArea: 'tes', townCity: 'test', zipCode: '121212', addressEmirate: 'ABU DHABI', addressPoBox: 'test', country: 'AF', addressStayingAtThis: '', mailingAddress: 'Y', primaryMobileNumber: '12212121', officeTelephoneNumber: '2121212', homeTelephoneNumber: '121212121', fax: '12121221', emailAddress: '1212@wqwq.dsadas', nearestLandmark: 'test',
          }, {
            addressiOrderId: '338', addressType: 'Correspondence', buildingNumber: 'test', buildingName: 'test', streetName: 'test', locationArea: 'tes', townCity: 'test', zipCode: '121212', addressEmirate: 'ABU DHABI', addressPoBox: 'test', country: 'AF', addressStayingAtThis: '', mailingAddress: 'Y', primaryMobileNumber: '12212121', officeTelephoneNumber: '2121212', homeTelephoneNumber: '121212121', fax: '12121221', emailAddress: '1212@wqwq.dsadas', nearestLandmark: 'test',
          }, {
            addressiOrderId: '324', addressType: 'Correspondence', buildingNumber: 'test', buildingName: 'test', streetName: 'test', locationArea: 'tes', townCity: 'test', zipCode: '121212', addressEmirate: 'ABU DHABI', addressPoBox: 'test', country: 'AF', addressStayingAtThis: '', mailingAddress: 'Y', primaryMobileNumber: '12212121', officeTelephoneNumber: '2121212', homeTelephoneNumber: '121212121', fax: '12121221', emailAddress: '1212@wqwq.dsadas', nearestLandmark: 'test',
          }, {
            addressiOrderId: '326', addressType: 'Correspondence', buildingNumber: 'test', buildingName: 'test', streetName: 'test', locationArea: 'tes', townCity: 'test', zipCode: '121212', addressEmirate: 'ABU DHABI', addressPoBox: 'test', country: 'AF', addressStayingAtThis: '', mailingAddress: 'Y', primaryMobileNumber: '12212121', officeTelephoneNumber: '2121212', homeTelephoneNumber: '121212121', fax: '12121221', emailAddress: '1212@wqwq.dsadas', nearestLandmark: 'test',
          }, {
            addressiOrderId: '328', addressType: 'Correspondence', buildingNumber: 'test', buildingName: 'test', streetName: 'tests', locationArea: 'tes', townCity: 'test', zipCode: '121212', addressEmirate: 'ABU DHABI', addressPoBox: 'test', country: 'AF', addressStayingAtThis: '', mailingAddress: 'Y', primaryMobileNumber: '12212121', officeTelephoneNumber: '2121212', homeTelephoneNumber: '121212121', fax: '12121221', emailAddress: '1212@wqwq.dsadas', nearestLandmark: 'test',
          }, {
            addressiOrderId: '329', addressType: 'Correspondence', buildingNumber: 'test', buildingName: 'test', streetName: 'tests', locationArea: 'tes', townCity: 'test', zipCode: '121212', addressEmirate: 'ABU DHABI', addressPoBox: 'test', country: 'AF', addressStayingAtThis: '', mailingAddress: 'Y', primaryMobileNumber: '12212121', officeTelephoneNumber: '2121212', homeTelephoneNumber: '121212121', fax: '12121221', emailAddress: '1212@wqwq.dsadas', nearestLandmark: 'test',
          }, {
            addressiOrderId: '330', addressType: 'Correspondence', buildingNumber: 'test', buildingName: 'test', streetName: 'tests', locationArea: 'tes', townCity: 'test', zipCode: '121212', addressEmirate: 'ABU DHABI', addressPoBox: 'test', country: 'AF', addressStayingAtThis: '', mailingAddress: 'Y', primaryMobileNumber: '12212121', officeTelephoneNumber: '2121212', homeTelephoneNumber: '121212121', fax: '12121221', emailAddress: '1212@wqwq.dsadas', nearestLandmark: 'test',
          }, {
            addressiOrderId: '331', addressType: 'Correspondence', buildingNumber: 'test2', buildingName: 'test', streetName: 'tests', locationArea: 'tes', townCity: 'test', zipCode: '121212', addressEmirate: 'ABU DHABI', addressPoBox: 'test', country: 'AF', addressStayingAtThis: '', mailingAddress: 'Y', primaryMobileNumber: '12212121', officeTelephoneNumber: '2121212', homeTelephoneNumber: '121212121', fax: '12121221', emailAddress: '1212@wqwq.dsadas', nearestLandmark: 'test',
          }, {
            addressiOrderId: '332', addressType: 'Correspondence', buildingNumber: 'test2', buildingName: 'test', streetName: 'tests', locationArea: 'tes', townCity: 'test', zipCode: '121212', addressEmirate: 'ABU DHABI', addressPoBox: 'test', country: 'AF', addressStayingAtThis: '', mailingAddress: 'Y', primaryMobileNumber: '12212121', officeTelephoneNumber: '2121212', homeTelephoneNumber: '121212121', fax: '12121221', emailAddress: '1212@wqwq.dsadas', nearestLandmark: 'test',
          }, {
            addressiOrderId: '333', addressType: 'Correspondence', buildingNumber: 'test2', buildingName: 'test', streetName: 'tests', locationArea: 'tes', townCity: 'test', zipCode: '121212', addressEmirate: 'ABU DHABI', addressPoBox: 'test', country: 'AF', addressStayingAtThis: '', mailingAddress: 'Y', primaryMobileNumber: '12212121', officeTelephoneNumber: '2121212', homeTelephoneNumber: '121212121', fax: '12121221', emailAddress: '1212@wqwq.dsadas', nearestLandmark: 'test',
          }, {
            addressiOrderId: '325', addressType: 'Correspondence', buildingNumber: 'test', buildingName: 'test', streetName: 'test', locationArea: 'tes', townCity: 'test', zipCode: '121212', addressEmirate: 'ABU DHABI', addressPoBox: 'test', country: 'AF', addressStayingAtThis: '', mailingAddress: 'Y', primaryMobileNumber: '12212121', officeTelephoneNumber: '2121212', homeTelephoneNumber: '121212121', fax: '12121221', emailAddress: '1212@wqwq.dsadas', nearestLandmark: 'test',
          }, {
            addressiOrderId: '327', addressType: 'Correspondence', buildingNumber: 'test', buildingName: 'test', streetName: 'test', locationArea: 'tes', townCity: 'test', zipCode: '121212', addressEmirate: 'ABU DHABI', addressPoBox: 'test', country: 'AF', addressStayingAtThis: '', mailingAddress: 'Y', primaryMobileNumber: '12212121', officeTelephoneNumber: '2121212', homeTelephoneNumber: '121212121', fax: '12121221', emailAddress: '1212@wqwq.dsadas', nearestLandmark: 'test',
          }, {
            addressiOrderId: '339', addressType: 'Correspondence', buildingNumber: 'test', buildingName: 'test', streetName: 'test', locationArea: 'tes', townCity: 'test', zipCode: '121212', addressEmirate: 'ABU DHABI', addressPoBox: 'test', country: 'AF', addressStayingAtThis: '', mailingAddress: 'Y', primaryMobileNumber: '12212121', officeTelephoneNumber: '2121212', homeTelephoneNumber: '121212121', fax: '12121221', emailAddress: '1212@wqwq.dsadas', nearestLandmark: 'test',
          }],
        },
        identityDetails: {
          identity: [{
            identityiOrderId: '339', identifiertype: 'PASSPORT', number: 'test', issuedate: '2022-12-03', expirydate: '2022-12-05', placeofissue: 'testasd',
          }],
        },
        taxClassification: {
          additionalFATCA: null, crsClaasification: null, usTaxClaasification: null, preliminaryTaxAssesment: null, fatcaDetails: null,
        },
        posLoanDetails: null,
        posExistingBankDetails: null,
        posCustomerList: null,
        posSupplierList: null,
        posBusinessFinancials: {
          posBusinessFinancialsiOrderID: null, posTurnOverFromAllAcquirers: '', posTurnOverBusinessFinancial: null, posBusinessFinancialDetails: null,
        },
        mbbfLoanDetails: null,
        mbbfFinancialDetails: null,
        mbbfExistingBankDetails: null,
        mbbfLoanPropertyDetails: null,
        businessLoans: null,
        kcpAppDetail: {
          kcpApplicant: {
            kcpApplicantIOrderId: '', title: '', fullName: '', firstName: '', lastName: '', gender: '', mothersMaidenName: '', dateOfbirth: '', countryOfBirth: '', placeOfBirth: '', countryOfResidence: '', nationality_Citizenship: '', otherNationality: '', residentStatus: '', yearsOfResidenceinUae: '', yearsInBusiness: '', maritalStatus: '', numberOfDependents: '', designation: '', isAuth: '', authName: '',
          },
          kcpAddressDetails: null,
          kcpIdentityDetails: null,
          kcpReferences: null,
        },
        businessAccount: null,
        registrationDetails: {
          rmCode: 'saff', firstName: 'asda', lastName: '4545454545', phoneNumber: 'asd', emailID: 'adasd@fsd.dfs',
        },
      },
    },
    statusCode: '0',
    status: 'Success',
    message: 'Workitem data fetched successfully',
    sysRefNo: '1672167675521',
  };
  const connectedObj = {
    dataArea: {
      captureRequest: {
        sysRefNo: '4e30049b-4edc-42a7-a8be-f14e042de1d47do-fab-demo14',
        initiatedBy: 'balamadesh1234',
        channel: 'PORTAL',
        productType: 'BA',
        source: 'P',
        isWorkitemCreate: 'M',
        folderIndex: '6578',
        wiUrn: 'SME-5046',
        wiName: 'SME-0000005046-process',

      },
      customerDetails: {
        registrationDetails: {
          rmCode: 'saff',
          firstName: 'bala',
          lastName: 'madesh',
          phoneNumber: '243243422',
          emailID: 'balamadesh@gmail.com',
	  },
        applicationDetail: {
          appDetailIOrderId: '1234',
          created_date: '',
          new_or_existing_customer: 'New',
          product: 'BA',
          loan_type: 'Fresh',
          loan_account_number: '',
          legal_entity_name: 'Legal1',
          cif_id: '',
          emirates_id: '',
          trade_license_number: 'bond1234',
          branch: '',
          channel: 'PORTAL',
        },
        customerDetail: {
          customeriOrderId: '1234',
          short_name: 'RAM',
          country_of_incorporation: 'AE',
          country_of_domiciles: 'AE',
          business_operation: '',
          date_of_incorporation: '2022-12-20 00:00:00.0',
          website_address: 'www@abc.com',
          emirate_of_registration: 'DUBAI',
          legal_entity_type: 'Free Zone - Offshore',
          legal_entity_category: 'Free Zone Entity',
          primary_industry: 'Maintenance of Building',
          secondary_industry: '',
          number_of_employes: 'null',
          current_company_turnoer: null,
          projected_company_turnover: null,
          sister_company: 'Y',
          legal_entity_name: null,
          group_name: null,
          registration_of_authority: null,
          registration_authority_name: null,
          vat: null,
          fab_sub_segment: null,
          sector: null,
          authorised_signatory: null,
          rollovertype: null,
          customer_status: null,
          business_details_description: null,
        },
        	addressDetails: {
          address: [
            {
              addressiOrderId: '1234',
              addressType: 'Correspondence',
              buildingNumber: '123',
              buildingName: 'ABC',
              streetName: 'Dubai',
              locationArea: 'Dubai',
              townCity: 'Dubai',
              zipCode: '600005',
              addressEmirate: 'ABU DHABI',
              addressPoBox: 'PO 67890',
              country: 'AE',
              addressStayingAtThis: '2018-07-12 00:00:00',
              mailingAddress: 'Y',
              primaryMobileNumber: '907890000',
              officeTelephoneNumber: '9023667788',
              homeTelephoneNumber: '890355665',
              fax: '9034566',
              emailAddress: 'zyz@gmail.com',
              nearestLandmark: 'Mall',
            },
          ],
        },
		  identityDetails: {
          identity: [
            {
              identityiOrderId: '1234',
              identifiertype: 'PASSPORT',
              number: '134566',
              issuedate: '2020-07-10 00:00:00.0',
              expirydate: '2029-03-01 00:00:00.0',
              placeofissue: 'Dubai',
            },
          ],
        },
	  connectedParties: {
          connectedPartiesDetails: [
            {
              connectedPartiesiOrderID: '1234',
              addressMapper: '149',
              identityMapper: '148',
              refMapper: '40',
              taxMapper: '57',
              connectedPartyType: 'CO-A',
              connectedPartyCIF: '',
              connectedPartyTitle: 'MR',
              connectedPartyFullName: 'RamPrasanth',
              connectedPartyFirstName: 'Bala',
              connectedPartyLastName: 'Prasanth',
              connectedPartyGender: 'M',
              connectedPartyMartialStatus: 'S',
              connectedPartyMothersMaidenName: 'ACD',
              connectedPartyDOB: '1994-03-01',
              connectedPartyCountryOfBirth: 'AE',
              connectedPartyPlaceOfBirth: 'UAE',
              connectedPartyNationality: 'AE',
              connectedPartyOtherNationality: 'AE',
              connectedPartyCountryOfResidence: 'AE',
              connectedPartyResidencyStatus: '',
              connectedPartyLegalEntityType: '',
              legalEntityCategory: '',
              connectedPartyShareHoldingAmount: '',
              connectedPartyShareHoldingPercentage: '',
              connectedPartyTypeOfOwnership: '',
              connectedPartyOwnershipStatus: '',
              connectedPartyBankingwithFAB: 'Y',
              connectedPartyFABAccountNumber: '3567888',
              connectedPartyUSPassport: 'Y',
              customerDetails: '',
              connectedPartyCountryOfIncorporation: '',
              connectedPartyDateOfIncorporation: '',
              connectedPartyCountryOfDomicile: '',
              connectedPartyCountryOfBusinessOperation: '',
              industryType: '',
              connectedPartyPrimaryIndustryType: '',
              connectedPartySecondaryIndustryType: '',
              connectedPartyOfficeTelephoneNumber: '56700000',
              connectedPartyWorkEmail: 'wead@gmail.com',
              connectedPartyPersonalEmail: 'fgh@gmail.com',
              connectedPartyRelationshipwithApplicant: 'HB',
              connectedPartyNoOfEmployees: '',
              connectedPartyAdditionalCompnayInfo: '',
              primaryMobileNumber: '',
              homeTelephoneNumber: '78846666',
              businessActivity: '',
              email: '',
              connectedPartyReferenceDetails: {
                connectedPartyReference: [
                  {
                    connectedPartyReferenceiOrderID: '',
                    connectedPartyReferenceType: 'UAE',
                    connectedPartyReferenceName: 'balaram',
                    connectedPartyReferenceMobileNumber: '12333222',
                    connectedPartyReferenceHomeTelephone: '678999',
                    connectedPartyReferenceOfficeTelephone: '790000',
                    connectedPartyReferenceRelationship: 'SP',
                  },
                  {
                    connectedPartyReferenceiOrderID: '',
                    connectedPartyReferenceType: 'UAE',
                    connectedPartyReferenceName: 'prasanthmadesh',
                    connectedPartyReferenceMobileNumber: '12333222',
                    connectedPartyReferenceHomeTelephone: '678999',
                    connectedPartyReferenceOfficeTelephone: '790000',
                    connectedPartyReferenceRelationship: 'SP',
                  },
                ],
              },
              connectedPartyaddressDetails: {
                connectedPartyaddress: [
                  {
                    connectedPartyaddressiOrderID: '',
                    connectedPartyaddressType: 'Correspondence',
                    connectedPartybuildingNumber: '123',
                    connectedPartybuildingName: 'ABC',
                    connectedPartystreetName: 'Street Name',
                    connectedPartyNearestLandmark: 'Mall',
                    connectedPartylocationArea: 'Madurai',
                    connectedPartytownCity: 'Madurai',
                    connectedPartyzipCode: '600035',
                    connectedPartyaddressEmirate: 'Madurai',
                    connectedPartyaddressPoBox: '890044',
                    connectedPartycountry: 'AE',
                    connectedPartyaddressStayingAtThis: '',
                    connectedPartymailingAddress: 'Y',
                    connectedPartyprimaryMobileNumber: '9090909090',
                    connectedPartyofficeTelephoneNumber: '56678900',
                    homeTelephoneNumber: '6745666',
                    connectedPartyfax: '235677',
                    connectedPartyemailAddress: 'abcd@gmail.com',
                  },
                ],
              },
              connectedPartyidentityDetails: {
                connectedPartyidentity: [
                  {
                    connectedPartyidentityiOrderID: '',
                    connectedPartyIdentifiertype: 'VISA',
                    connectedPartyIdentityNumber: '23567',
                    connectedPartyIdentityIssuedate: '2018-06-12',
                    connectedPartyIdentityExpirydate: '2028-07-13',
                    connectedPartyIdentityplaceofissue: 'Dubai',
                  },
                ],
              },
              connectedPartyTaxReferenceDetails: {
                connectedPartyTaxReference: [
                  {
                    connectedPartyTaxReferenceiOrderID: '',
                    connectedPartyTaxReferenceStandingInstructions: 'Y',
                    connectedPartyTaxReferenceInCareOfHold: 'Y',
                    connectedPartyTaxReferenceUsTaxFromClient: 'Y',
                    connectedPartyTaxReferenceIsUSResident: 'Y',
                    connectedPartyTaxReferenceIsUSCitizen: 'Y',
                    connectedPartyTaxReferenceIsUSGreenCard: 'Y',
                    connectedPartyTaxCountryOfBirth: 'AE',
                    connectedPartyTaxChapter3Status: 'Y',
                    connectedPartyTaxW9Exemption: 'A',
                    connectedPartyTaxUSTaxPersonStatus: 'Non U.S. Person (871M)',
                    connectedPartyTaxFormSignedDate: '2018-03-09',
                    connectedPartyTaxReportable: 'true',
                    connectedPartyTaxFromType: 'CRS &amp; FATCA Self-Certification Form',
                    connectedPartyTaxChapter4Status: '(Specified) U.S. Person',
                    connectedPartyTaxStartupDate: '2019-07-10',
                    connectedPartyTaxBankruptcyDate: '2022-06-01',
                    connectedPartyTaxNameOfSponsoring: 'YYYYYYY',
                    connectedPartyTaxUSOnshore: 'Y',
                    connectedPartyTaxIsDisregarded: 'T',
                    connectedPartyTaxFormReceived: '2019-07-18',
                    connectedPartyTaxIdentifierType: 'TIN',
                    connectedPartyTaxIdentifierNumber: '14455',
                    connectedPartyTaxCountryOfTax: 'AE',
                    connectedPartyTaxIsReportable: 'T',
                    connectedPartyTaxFATCAStatus: 'Non.US.Confirmed',
                    connectedPartyTaxTINUnavailableReason: 'Reason B: Account Holder unable to obtain TIN',
                    connectedPartyTaxTINUnavailableRemarks: 'Dee',
                    connectedPartyTaxNationality: 'AE',
                    connectedPartyTaxOtherNationality: 'AF',
                    connectedPartyTaxComments: 'AAA',
                    connectedPartyTaxCRSEntityType: 'Active NFE - A corporation the stock of which is regularly traded on an established securities market or a corporation which is a related entity of such a corporation',
                    connectedPartyTaxDocumentType: 'CRS Waiver',
                    connectedPartyTaxDocumentSignedDate: '2022-03-02',
                    connectedPartyTaxDocumentRecivedDate: '2022-03-10',
                    connectedPartyTaxVISAValidfor5years: 'Y',
                    connectedPartyTaxFullNameOFUBO: 'DFG',
                    connectedPartyTaxResidentInOtherJurisdictions: 'Y',
                    connectedPartyTaxResidentInOtherJurisdictionSubjectToPersonal: 'Ameerica',
                  },
                ],
              },
            },
          ],
        },
	 },
    },
  };

  return (
    <div>test</div>
  );
}

export default test;
